### ISSUE TITLE
Resseract still active?

### ISSUE THREAD

**Issue by lonnietc** [mbitsnbites/resseract#1]
Hello,

I am researching 3D engines (Tesseract, Unreal, O3DE, etc.) for a really exciting project and have come across your Resseract which seems to be improvements over Tesseract (http://tesseract.gg/)

I also know that Tesseract has not been worked on since 2014 and this it seems that Resseract  has not been updated in 5 years, but there are a number of features that these have which are desirable such as in-game editing and small footprints.

I would be interested to know if the project is still active or if you might consider discussing it more with me?

Thanks and have a great day

**Comment by mbitsnbites** [comment]
No, the project is no longer under development. Partly because I didn't have time to work with it, and partly because the SW architecture/style is ... very old and not perfect.

It's a shame - it's a pretty interesting piece of technology with nice and high performance graphics (IMO) and editing capabilities.

**Comment by lonnietc** [comment]
Yea, I really still like the concept of the Tesseract (Resseract) and Cube2 engines in that it has reasonably good performance graphics and built-in editor as well.  I thought that it would lay a great foundation for a modern engine, but the code is a bit old as you mention, and I do not know how much work it would take to make it modern in that regard as I do not know a lot of experience in graphics as well.

Lately, I am digging into the UnReal engine as I now have the source and am wondering if it might be possible to embed the editor into a game space like Tesseract to allow for in-game editing. The engine has an amazing level of photo-realistic graphics but also the engine is a bit heavy and requires a modern GPU to run efficiently whereas the Tesseract (and similar) seems to run reasonably well on a bit older system. 

I have a really good VR and virtual worlds, project that I have been waiting for many years for the technology (software and hardware) to catch up and now seems like the time to move it forward so the choices have come down to either taking Tesseract (Resseract) and work on updating it or take something like UnReal and build it out since hardware will always seem to evolve as people want better and better graphics, etc.

Just some thoughts, my friend.

**Comment by mbitsnbites** [comment]
Interesting. IIRC I actually tried to get Resseract (or Tesseract?) working with my Occulus DK2 a few years ago, but never had the time to make it work. My idea was that a dynamic/interactive/playable world editor as simple as the one in these games would be perfect for building VR worlds. The good rendering performance also seemed perfect for VR.

Good luck with your project!

**Comment by lonnietc** [comment]
Thanks for getting back to me on this and if you like, I'll keep you updated on the progress.

Still considering options and reviewing all of the possibilities but this is going to be a really exciting time for this type of project.

**Comment by lonnietc** [comment]
Hello,

I hope that all is well.  In the past we discussed Resseract and I am picking up a small effort to work on Tesseract since I have some really exciting ideas to possibly implement if I can get a good feel for the code.

With that in mind, I was wondering how complete your port of Tesseract (C-based) was to Resseract (C++ based) since I would like to use a C++ version and one of the first things that I have in mind is to see if it might be possible to upgrade the renderer from SDL to Vulkan or something like that to have a modern rendering engine to be able to produce substantially higher quality graphics.

Any thoughts from you would be greatly appreciated..

**Comment by lonnietc** [comment]
@mbitsnbites Hello, my friend.

I am I have been able to build up Tesseract and am doing some initial testing, but actually what to build up Ressearct since it is a CPP port and I will expand from there.

What I am wondering is if you were able to complete the Linux port and were able to compile and run the game with Resseract.

If so, then I will probably go ahead and switch over to your version and then try to build up a Visual Studio 2022 solution for it but wanted to get your input on things fist.

Thanks and have a great day.
